---
deployment:
  tasks:
    - export DEPLOYPATH=/home/Firstname-:fire/public_html/
    - export SOURCEPATH=/home/Firstname-:fire/repositories/kia-ora/
    - /bin/cp -R $SOURCEPATH/. $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production=false
    - npm run build
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.ts $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
    - /bin/cp -R prisma $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R types $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
